### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by mproyyan** [yusuftaufiq/laravel-books-api#26]
I was following your manual installation instruction correctly, but i got an error like this

![ssl_certificate](https://user-images.githubusercontent.com/67527166/170807510-9579ab31-cb43-4d24-a240-0ef675e2168c.PNG)

This error appear when i try to run the tests using command `php artisan test`, but when i try to access the endpoint using insomnia, the app runs normally

This is the test results, i got 7 failed tests and all errors are caused by ssl certificate problem

![tests](https://user-images.githubusercontent.com/67527166/170807927-ad4038d7-097d-4147-b93e-b58cf25cb7c5.PNG)

I'm new in programming, and i saw your code then i think your code is good for me to improve my skill
Hope you solve my issue
Thanks.

**Comment by yusuftaufiq** [comment]
Hi @mproyyan, thank you for reporting this issue.

Are you still getting that error when trying to run `php artisan test`? I have tried running `php artisan test` also on several devices but haven't gotten the error you mentioned.

**Comment by mproyyan** [comment]
yeah, i tried reinstall, update the composer, switch from laragon to laravel development server but still return the same errors

**Comment by yusuftaufiq** [comment]
Maybe this happens because there is an SSL certification incompatibility in the PHP you are using. To fix it, you can try the following steps:
1. Install CA Bundle with `composer require composer/ca-bundle`
2. Open `app/Providers/GoutteServiceProvider.php` & replace the register method with the following code:
    ```php
    $this->app->bind('goutte', fn () => new Client(
        HttpClient::create([
            'timeout' => self::HTTP_TIMEOUT,
            'cafile' => \Composer\CaBundle\CaBundle::getSystemCaRootBundlePath(),
        ])
    ));
    ```
3. Run `composer cache:clear` and `php artisan test`
4. Or if you still get the error you mentioned, you can try changing the code in the second step with the following code:
    ```php
    $this->app->bind('goutte', fn () => new Client(
        HttpClient::create([
            'timeout' => self::HTTP_TIMEOUT,
            'cafile' => \Composer\CaBundle\CaBundle::getBundledCaBundlePath(),
        ])
    ));
    ```
5. Or if you still get the error (this is probably not recommended), you can try turning off SSL verification with the following code:
    ```php
    $this->app->bind('goutte', fn () => new Client(
        HttpClient::create([
            'timeout' => self::HTTP_TIMEOUT,
            'verify_host' => false,
            'verify_peer' => false,
        ])
    ));
    ```
Let me know if this works.

**Comment by mproyyan** [comment]
Thank you, it worked

![test_passed](https://user-images.githubusercontent.com/67527166/170896646-ff592727-5034-4675-9af3-b856b25f770c.PNG)

**Comment by yusuftaufiq** [comment]
Glad to hear that, I will close this issue.
